catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground

catalog:
  bumpp: ^10.4.1
  mdream: ^0.15.3
  ofetch: ^1.5.1
  pathe: ^2.0.3
  std-env: ^3.10.0
  tsx: ^4.21.0
  unagent: ^0.0.8

catalogs:
  deps:
    '@clack/prompts': ^1.0.1
    '@huggingface/transformers': ^3.8.1
    citty: ^0.2.1
    consola: ^3.4.2
    globby: ^16.1.0
    log-update: ^7.1.0
    mlly: ^1.8.0
    oxc-parser: ^0.112.0
    p-limit: ^7.3.0
    retriv: ^0.10.0
    sqlite-vec: ^0.1.6
    typescript: beta
  dev-build:
    '@types/node': ^25.2.3
    obuild: ^0.4.27
  dev-lint:
    '@antfu/eslint-config': ^7.4.3
  dev-test:
    '@vitest/coverage-v8': ^4.0.18
    evalite: ^0.19.0
    vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
